### ISSUE TITLE
entity_record_collection::_preload_many_to_many() Cannot Support Offset/Limit/Orderby

### ISSUE THREAD

**Issue by nfrm** [neoform/PHP-Neoform#12]
Logic error: Many to Many relationships cannot be filtered with limit/offsets. This doesn't cause a bug, it just doesn't work and is ignored when used.

**Comment by neoform** [comment]
This has been removed, however I want to find a way to actually do this if possible.

Example of a possibly large many to many relationship would be club -> club_member -> member.

**Comment by neoform** [comment]
The answer is no. This wouldn't make sense.
